# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170219_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_address',
            new_name='voter_address',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='voter_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='ballot',
            name='ballot_address',
            field=models.CharField(default='Enter Valid Ballot Address', max_length=36),
            preserve_default=False,
        ),
    ]
