# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170325_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ballot',
            old_name='ballot_text',
            new_name='ballot_name',
        ),
    ]
