# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170331_0852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='VoterChoice',
        ),
    ]
