# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_contestantchoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voterchoice',
            old_name='voter_text',
            new_name='voter_name',
        ),
    ]
