# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_ballot_isitvoter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestantchoice',
            name='ballot',
        ),
        migrations.DeleteModel(
            name='ContestantChoice',
        ),
    ]
