# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20170331_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestantchoice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contestantchoice',
            name='contestant_address',
            field=models.CharField(choices=[('mujVHE4aQ21SQDeDmg3kSyg37jFnTprUPy', 'contestant1Address'), ('mwxTvJ8zxziSeW7J357QxTWF534QMCEtsY', 'contestant2Address')], max_length=36),
        ),
    ]
