# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20170401_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotersList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voters', models.CharField(choices=[('mpMtRQUB9XeyXiJevZL6TuLxbvNJJys74j', 'Voter1Address'), ('miyLyx2bp4buCnRV4y93RKNH3Lp1s89zQa', 'voter2Address'), ('n39HtcDLnXrxNH4yEra8K7QfVKLN2CJ3Sk', 'voter3Address')], default='Voter1Address', max_length=36)),
            ],
        ),
    ]
