# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20170405_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotersListChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voters', models.CharField(choices=[('mpMtRQUB9XeyXiJevZL6TuLxbvNJJys74j', 'Voter1Address'), ('miyLyx2bp4buCnRV4y93RKNH3Lp1s89zQa', 'voter2Address'), ('n39HtcDLnXrxNH4yEra8K7QfVKLN2CJ3Sk', 'voter3Address')], max_length=36)),
            ],
        ),
        migrations.RemoveField(
            model_name='voterslist',
            name='voters',
        ),
        migrations.AddField(
            model_name='voterslist',
            name='votersList_name',
            field=models.CharField(default='Enter Voters List Name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voterslistchoice',
            name='ballot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listvoters', related_query_name='listvoters', to='polls.VotersList'),
        ),
    ]
