# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20170406_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voterslistchoice',
            old_name='ballot',
            new_name='voterlist',
        ),
    ]
