# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20170406_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterslistchoice',
            name='voters',
        ),
        migrations.AddField(
            model_name='voterslistchoice',
            name='voter_address',
            field=models.CharField(choices=[('mpMtRQUB9XeyXiJevZL6TuLxbvNJJys74j', 'Voter1Address'), ('miyLyx2bp4buCnRV4y93RKNH3Lp1s89zQa', 'Voter2Address'), ('n39HtcDLnXrxNH4yEra8K7QfVKLN2CJ3Sk', 'Voter3Address')], default='Enter Voter Address', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voterslistchoice',
            name='voter_name',
            field=models.CharField(choices=[('Voter1Address', 'Voter1Address'), ('Voter2Address', 'Voter2Address'), ('Voter3Address', 'Voter3Address')], default='Enter Voter Name', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voterchoice',
            name='voter_address',
            field=models.CharField(choices=[('mpMtRQUB9XeyXiJevZL6TuLxbvNJJys74j', 'Voter1Address'), ('miyLyx2bp4buCnRV4y93RKNH3Lp1s89zQa', 'Voter2Address'), ('n39HtcDLnXrxNH4yEra8K7QfVKLN2CJ3Sk', 'Voter3Address')], max_length=36),
        ),
    ]
