# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20170406_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterslistchoice',
            name='voter_name',
            field=models.CharField(choices=[('Voter1', 'Voter1'), ('Voter2', 'Voter2'), ('Voter3', 'Voter3')], max_length=200),
        ),
    ]
