# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_voterslistchoice_currentvoterchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterslistchoice',
            name='currentVoterChoice',
        ),
        migrations.AddField(
            model_name='voterslist',
            name='currentVoterChoice',
            field=models.CharField(default='', max_length=36),
            preserve_default=False,
        ),
    ]
