# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20170406_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestantchoice',
            name='confirmedVotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contestantchoice',
            name='unconfirmedVotes',
            field=models.IntegerField(default=0),
        ),
    ]
