# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20170414_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestantchoice',
            name='unconfirmedVotes',
        ),
        migrations.AddField(
            model_name='ballot',
            name='unconfirmedVotes',
            field=models.IntegerField(default=0),
        ),
    ]
