# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20170415_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ballot',
            old_name='unconfirmedVotes',
            new_name='totalUnconfirmedVotes',
        ),
    ]
