# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_auto_20170415_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='currentUnconfirmedVotes',
            field=models.IntegerField(default=0),
        ),
    ]
