# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_auto_20170415_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterchoice',
            name='voter_address',
            field=models.CharField(choices=[('mpMtRQUB9XeyXiJevZL6TuLxbvNJJys74j', 'Voter1Address'), ('miyLyx2bp4buCnRV4y93RKNH3Lp1s89zQa', 'Voter2Address'), ('n39HtcDLnXrxNH4yEra8K7QfVKLN2CJ3Sk', 'Voter3Address'), ('mprd13H5FSBYH51Eznvhhwn89Mkny9u1zH', 'Voter4Address'), ('mm7LYV3aNxEd45RcgGU7WD29JPqcBRBUSn', 'Voter5Address'), ('mz7fyLU79MWuCo6vZTyhEnGbsAbr64J5BB', 'Voter6Address'), ('mjzUjupW4LdNb56mNnj9DNDjpagowjgY99', 'Voter7Address'), ('mocxZTDcRP1XtBFc3EeAqScF1ahCmVV7uH', 'Voter8Address'), ('mzEa7GNeM4a77z5h9maWZVP9NKUaAvJo7h', 'Voter9Address'), ('mqE9f1YBdSkoovUQmQ1WCUoRbDWxt2tTtf', 'Voter10Address'), ('msf3JRk8aATVzKafhS1XE9eXLyWvNfgEQc', 'Voter11Address'), ('n4eRLRVVMXzEjWyhpPtJiQkJroX3NMydvj', 'Voter12Address'), ('mgsG2zssbMXKdDebSMCDDqC38wrkJZdB7V', 'Voter13Address'), ('mjxBEdw3cTZEdqADtv3TVGQMYJ4Ug6mMey', 'Voter14Address'), ('mh5uSJz9peDod9k4eDvCnDJreSBhMZXcUg', 'Voter15Address'), ('mxTBS9bmg2xToB3mrVjUBAhiZZyPi9Wy5u', 'Voter16Address'), ('mtfS7aoiURB8gwF3sBVdF2frEE8sdMrRJP', 'Voter17Address'), ('mwZ4nP3ZcUbAsD9nxQiih9Q3i7XcWTBcAX', 'Voter18Address'), ('mgaSJrRHGzPsCGxvWoZXwSzyWfG1m3pfqe', 'Voter19Address'), ('mxmfKdzYyxxjD1rz9rba7hBqWsfbbVSEcN', 'Voter20Address')], max_length=36),
        ),
        migrations.AlterField(
            model_name='voterslistchoice',
            name='voter_address',
            field=models.CharField(choices=[('mpMtRQUB9XeyXiJevZL6TuLxbvNJJys74j', 'Voter1Address'), ('miyLyx2bp4buCnRV4y93RKNH3Lp1s89zQa', 'Voter2Address'), ('n39HtcDLnXrxNH4yEra8K7QfVKLN2CJ3Sk', 'Voter3Address'), ('mprd13H5FSBYH51Eznvhhwn89Mkny9u1zH', 'Voter4Address'), ('mm7LYV3aNxEd45RcgGU7WD29JPqcBRBUSn', 'Voter5Address'), ('mz7fyLU79MWuCo6vZTyhEnGbsAbr64J5BB', 'Voter6Address'), ('mjzUjupW4LdNb56mNnj9DNDjpagowjgY99', 'Voter7Address'), ('mocxZTDcRP1XtBFc3EeAqScF1ahCmVV7uH', 'Voter8Address'), ('mzEa7GNeM4a77z5h9maWZVP9NKUaAvJo7h', 'Voter9Address'), ('mqE9f1YBdSkoovUQmQ1WCUoRbDWxt2tTtf', 'Voter10Address'), ('msf3JRk8aATVzKafhS1XE9eXLyWvNfgEQc', 'Voter11Address'), ('n4eRLRVVMXzEjWyhpPtJiQkJroX3NMydvj', 'Voter12Address'), ('mgsG2zssbMXKdDebSMCDDqC38wrkJZdB7V', 'Voter13Address'), ('mjxBEdw3cTZEdqADtv3TVGQMYJ4Ug6mMey', 'Voter14Address'), ('mh5uSJz9peDod9k4eDvCnDJreSBhMZXcUg', 'Voter15Address'), ('mxTBS9bmg2xToB3mrVjUBAhiZZyPi9Wy5u', 'Voter16Address'), ('mtfS7aoiURB8gwF3sBVdF2frEE8sdMrRJP', 'Voter17Address'), ('mwZ4nP3ZcUbAsD9nxQiih9Q3i7XcWTBcAX', 'Voter18Address'), ('mgaSJrRHGzPsCGxvWoZXwSzyWfG1m3pfqe', 'Voter19Address'), ('mxmfKdzYyxxjD1rz9rba7hBqWsfbbVSEcN', 'Voter20Address')], max_length=36),
        ),
        migrations.AlterField(
            model_name='voterslistchoice',
            name='voter_name',
            field=models.CharField(choices=[('Voter1', 'Voter1'), ('Voter2', 'Voter2'), ('Voter3', 'Voter3'), ('Voter4', 'Voter4'), ('Voter5', 'Voter5'), ('Voter6', 'Voter6'), ('Voter7', 'Voter7'), ('Voter8', 'Voter8'), ('Voter9', 'Voter9'), ('Voter10', 'Voter10'), ('Voter11', 'Voter11'), ('Voter12', 'Voter12'), ('Voter13', 'Voter13'), ('Voter14', 'Voter14'), ('Voter15', 'Voter15'), ('Voter16', 'Voter16'), ('Voter17', 'Voter17'), ('Voter18', 'Voter18'), ('Voter19', 'Voter19'), ('Voter20', 'Voter20')], max_length=200),
        ),
    ]
