# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_auto_20170415_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestantchoice',
            name='unconfirmedVotes',
            field=models.IntegerField(default=0),
        ),
    ]
