# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_contestantchoice_unconfirmedvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterchoice',
            name='sendAddr',
            field=models.CharField(default='None', max_length=36),
        ),
    ]
