# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_voterchoice_sendaddr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballot',
            name='currentUnconfirmedVotes',
        ),
        migrations.RemoveField(
            model_name='ballot',
            name='totalUnconfirmedVotes',
        ),
    ]
