# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_auto_20170418_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestantchoice',
            name='votes',
        ),
    ]
