# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_remove_contestantchoice_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestantchoice',
            name='contestant_address',
            field=models.CharField(choices=[('mujVHE4aQ21SQDeDmg3kSyg37jFnTprUPy', 'contestant1Address'), ('mwxTvJ8zxziSeW7J357QxTWF534QMCEtsY', 'contestant2Address'), ('mygJdFGURTEsNLZs4tUuxBHmTxnriH3i6y', 'contestant3Address'), ('n4P1Hzeis1AdWSp8d3xrDmPepatKmQL7Pz', 'contestant4Address'), ('mgVAPC3Yow3K2wDx8bP25XrXbd1G5nvqyn', 'contestant5Address'), ('mqaKWkQevJDpBSuBx7i45gaytiyYwf1KJW', 'contestant6Address'), ('mkNYWRhzY74rJ8QRH9nMHGADEwYSnp2Q5c', 'contestant7Address'), ('n3qswyanPxpRDzihvzwRpuV3zdUi3MDuAx', 'contestant8Address'), ('mvYejuDNRECgfhgGBGdHyhNsHYZBD5tMdm', 'contestant9Address'), ('n3JK9sGRSHwYVipaVh5Ly8j51S3hJCa1PE', 'contestant10Address')], max_length=36),
        ),
    ]
